apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webapp
spec:
  minReplicas: 1
  maxReplicas: 50
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: webapp
  targetCPUUtilizationPercentage: 30